[pytest]

addopts = --headed
          --browser=chromium
          --video=retain-on-failure
;          --screenshot=only-on-failure
          --tracing=retain-on-failure
          --html=myreport.html --self-contained-html --capture=tee-sys
;          if you want to add timestamp to myreport title, you need to command the line#8 and manually run below pytest command in terminal
;          pytest test_sample.py --html=reports/report_$(date +"%Y-%m-%d_%H-%M-%S").html --self-contained-html
          --alluredir=reports/allure-results
